// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAppv3.Data;

namespace WeatherAppv3.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211017222647_ExtendedCityEntity")]
    partial class ExtendedCityEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WeatherAppv3.Entities.AppCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WeatherAppv3.Entities.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppCityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rainfall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindSpeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppCityId");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("WeatherAppv3.Entities.Weather", b =>
                {
                    b.HasOne("WeatherAppv3.Entities.AppCity", "AppCity")
                        .WithMany("WeatherData")
                        .HasForeignKey("AppCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppCity");
                });

            modelBuilder.Entity("WeatherAppv3.Entities.AppCity", b =>
                {
                    b.Navigation("WeatherData");
                });
#pragma warning restore 612, 618
        }
    }
}
